### ISSUE TITLE
Plik fazy1 w folderze fazy2

### ISSUE THREAD

**Issue by hansiu** [pbiecek/ProgramowanieWizualizacja#44]
[https://github.com/pbiecek/ProgramowanieWizualizacja/blob/master/MIMUW_2017/Projekty/Projekt1/Faza2/ZbijewskaKranas1/ZbijewskaKranas1-1.html](url)

ten plik powinien znaleźć się w folderze fazy 1, a nie 2.

**Comment by pbiecek** [comment]
zmienione z  b5048abb3a6b4b000623293f60af412fb7664c83
