### ISSUE TITLE
Link do pakietu N. Kneblewska i R. Cylwa

### ISSUE THREAD

**Issue by rcylwa** [pbiecek/ProgramowanieWizualizacja#55]
install_github("rcylwa/SuperFarmerRCNK")

**Comment by DLme1** [comment]
[SuperFarmerMoc_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/635944/SuperFarmerMoc_0.0.0.9000.tar.gz)

**Comment by ambroziakd** [comment]
Przemysław Dycha, Dominik Ambroziak

# install.packages("devtools")
devtools::install_github("ambroziakd/KursRprojekt2/SuperFarmerDA")

repozytorium:
https://github.com/ambroziakd/KursRprojekt2/tree/master/SuperFarmerDA

**Comment by DLme1** [comment]
Wyniki 3 pakietów
[korzystaniePakiet.zip](https://github.com/pbiecek/ProgramowanieWizualizacja/files/636054/korzystaniePakiet.zip)
