### ISSUE TITLE
Faza II

### ISSUE THREAD

**Issue by hansiu** [pbiecek/ProgramowanieWizualizacja#56]
nasze pakiety

**Comment by Jusira** [comment]
[SuperFarmerAGOJZB_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639207/SuperFarmerAGOJZB_0.0.0.9000.tar.gz)

**Comment by hansiu** [comment]
https://github.com/hansiu/SuperFarmer.SuperDziewczyn/

i 

[SuperFarmer.SuperDziewczyn_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639209/SuperFarmer.SuperDziewczyn_0.0.0.9000.tar.gz)

**Comment by byrolew** [comment]
link https://github.com/byrolew/SuperFarmerMAPA

**Comment by pm27** [comment]
[SuperFarmer.SuperPakiet_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639240/SuperFarmer.SuperPakiet_0.0.0.9000.tar.gz)

**Comment by joannazbijewska** [comment]
[SuperFarmerAGOJZB_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639260/SuperFarmerAGOJZB_0.0.0.9000.tar.gz)
Zmieniona wersja R.

**Comment by PiotrRadzinski** [comment]
[SuperFarmerADiPR_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639278/SuperFarmerADiPR_0.0.0.9000.tar.gz)
Nazwy strategii: strategia_ADA oraz strategia_postMDiPR

**Comment by pm27** [comment]
3.0.0
[SuperFarmer.SuperPakiet_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639282/SuperFarmer.SuperPakiet_0.0.0.9000.tar.gz)

**Comment by pm27** [comment]
Poprawiona wersja pakietu, aby strategie z innych pakietów działały na naszej grze.

[SuperFarmer.SuperPakiet_0.0.0.9000.tar.gz](https://github.com/pbiecek/ProgramowanieWizualizacja/files/639403/SuperFarmer.SuperPakiet_0.0.0.9000.tar.gz)
