### ISSUE TITLE
Umieszczenie plików Fazy2

### ISSUE THREAD

**Issue by Jusira** [pbiecek/ProgramowanieWizualizacja#57]
W którym folderze należy umieszczać nasze pakiety i linki do filmów?

**Comment by pbiecek** [comment]
Proszę dodać do katalogu
https://github.com/pbiecek/ProgramowanieWizualizacja/tree/master/MIMUW_2017/Projekty/Projekt2
Można wkopiować pakiet i opis lub umieścić link do repozytorium w którym jest pakiet i opis
