### ISSUE TITLE
pytanie do fazy 3

### ISSUE THREAD

**Issue by hansiu** [pbiecek/ProgramowanieWizualizacja#68]
Czy w fazie 3 zakładamy możliwość modyfikacji pakietów (na potrzeby tworzenia wizytówek) czy jest to zakazane?

**Comment by pbiecek** [comment]
Można dowolnie zmieniać pakiet, dodawać, usuwać funkcje

**Comment by hansiu** [comment]
dziękuję za odpowiedź :)
